name: Daily Trading Signal

on:
  schedule:
    # Runs at 19:45 UTC every Monday through Friday
    # Vancouver (PT):
    # - Summer (PDT): 12:45 PM (15 mins before close)
    # - Winter (PST): 11:45 AM (1 hr 15 mins before close)
    - cron: '45 19 * * 1-5'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Backtest & Send Signal
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python backtest.py
